config/routes.rb
Rails.application.routes.draw do

  root 'players#index'

  get '/players/:age/:player1/:player2' => 'players#ajax'

  resources :players, only: [:index, :show]

end

app/models/player.rb
class Player < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  validates :age, presence: true

  def self.search(query)
      where('name LIKE ?', "%#{query}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def ajax

    player1 = Player.find_by({ age: params['age'], name: params['player1'].titleize })

    player2 = Player.find_by({ age: params['age'], name: params['player2'].titleize })

    render :json => [ player1, player2 ]

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>MLB Stat Comparison</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<div class="container-fluid">

  <div class="form-group">
    <div class="row">
      <h1 class="text-center title">MLB Player Comparison</h1>
    </div>
</div>

  <div class="text-center">
    <h4>Enter two players and the age at which you would like to compare their stats.</h4>
    <h4>For example:  20, Bryce Harper, Mike Trout</h4>
  </div>

  <div class="container-fluid">

      <%= form_tag(players_path, :method => "GET", id: "form") do %>

        <div class="buttons">
          <%= text_field_tag :age, params[:age], placeholder: "Age", id: "age" %>
          <%= text_field_tag :search1, params[:search1], placeholder: "Player 1", id: "player1" %>
          <%= text_field_tag :search2, params[:search2], placeholder: "Player 2", id: "player2" %>
        </div>

        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4" ><button id="searchbutton" class="btn btn-primary" type="submit">SEARCH</button></div>
          <div class="col-md-4"></div>
        </div>   <!-- new bootstrap button -->

      <% submit_tag "Search", :name => nil, id: "submit" %> <!-- submit - invisible -->

    <% end %>  <!-- form_tag -->

  </div> <!-- form-group -->
</div><!--  container -->



<div class="container-fluid">
  <div class="row1">
    <div class="col-md-1" id="name1"></div>
    <div class="col-md-1" id="hr1"></div>
    <div class="col-md-1" id="avg1"></div>
    <div class="col-md-1" id="r1"></div>
    <div class="col-md-1" id="bb1"></div>
    <div class="col-md-1" id="so1"></div>
    <div class="col-md-1" id="rbi1"></div>
    <div class="col-md-1" id="sb1"></div>
    <div class="col-md-1" id="obp1"></div>
    <div class="col-md-1" id="slg1"></div>
    <div class="col-md-1" id="ops1"></div>
    <div class="col-md-1" id="iso1"></div>
  </div>
</div>

<div class="container-fluid">
  <div class="row2">
    <div class="col-md-1" data-toggle="tooltip" data-placement="right" title="NAME"><h4>NAME</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="HOME RUNS"><h4>HR</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="AVERAGE"><h4>AVG</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="RUNS"><h4>R</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="WALKS"><h4>BB</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="STRIKE OUTS"><h4>SO</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="RUNS BATTED IN"><h4>RBI</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="STOLEN BASES"><h4>SB</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="ON BASE PERCENTAGE"><h4>OBP</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="SLUGGING"><h4>SLG</h4></div>
    <div class="col-md-1" data-toggle="tooltip" title="ON-BASE PLUS SLUGGING"><h4>OPS</h4></div>
    <div class="col-md-1" data-toggle="tooltip" data-placement="left" title="ISOLATED POWER"><h4>ISO</h4></div>
  </div>
</div>

<div class="container-fluid">
  <div class="row3">
    <div class="col-md-1" id="name2"></div>
    <div class="col-md-1" id="hr2"></div>
    <div class="col-md-1" id="avg2"></div>
    <div class="col-md-1" id="r2"></div>
    <div class="col-md-1" id="bb2"></div>
    <div class="col-md-1" id="so2"></div>
    <div class="col-md-1" id="rbi2"></div>
    <div class="col-md-1" id="sb2"></div>
    <div class="col-md-1" id="obp2"></div>
    <div class="col-md-1" id="slg2"></div>
    <div class="col-md-1" id="ops2"></div>
    <div class="col-md-1" id="iso2"></div>
  </div>
</div>

<!-- bootstrap function for tooltip -->
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
<!-- end bootstrap tooltip -->

<!-- charts start here -->
<div class="container-fluid">
  <div class="col-sm-6">
    <canvas id="canvas" height="50%" width="50%"></canvas>
  </div>

  <div class="col-sm-6">
    <canvas id="canvas2" height="50%" width="50%"></canvas>
  </div>
</div> <!-- container -->

<div class="container-fluid">
  <div class="col-md-4"></div>
    <div class="col-md-4">
      <canvas id="chart-area" width="50%" height="50%"></canvas>
    </div>
  <div class="col-md-4"></div>
</div> <!-- container -->

<div class="container">
  <div class="centered text-center"></div>
    <div style="width: 75%">
      <canvas id="canvas3" height="450" width="600"></canvas>
    </div>
  <div class="col-md-4"></div>
</div> <!-- container -->

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Name/Age Error</h4>
        </div>
        <div class="modal-body">
          <p>Please try submitting a valid name or age.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>




    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"> </script>
</body>
</html>